services:
    sonata.admin.post:
        class: Wagaia\Bundle\CMSBundle\Admin\PageAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Page" }
        arguments:
            - ~
            - Wagaia\Bundle\CMSBundle\Entity\Page
            - ~
        calls:
            - [ setTranslationDomain, [WagaiaCMSBundle]]