services:
    wagaia_cms.admin.post:
        class: Wagaia\Bundle\CMSBundle\Admin\PageAdmin
        arguments: [~, Wagaia\Bundle\CMSBundle\Entity\Page, WagaiaCMSBundle:Page]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Page }

    wagaia_cms.admin.menu:
        class: Wagaia\Bundle\CMSBundle\Admin\MenuAdmin
        arguments: [~, Wagaia\Bundle\CMSBundle\Entity\Menu, WagaiaCMSBundle:MenuAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Menu}

    wagaia_cms.admin.menu_item:
        class: Wagaia\Bundle\CMSBundle\Admin\MenuItemAdmin
        arguments: [~, Wagaia\Bundle\CMSBundle\Entity\MenuItem, WagaiaCMSBundle:MenuItemAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: MenuItem}
