parameters:
#    wagaia_cms.example.class: Wagaia\Bundle\CMSBundle\Example

services:
    wagaia_main.menu_builder:
        class: Wagaia\Bundle\CMSBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]

    wagaia_main.menu.main:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: wagaia_main.menu_builder
        factory_method: createMainMenu
        arguments: ["@request"]
        scope: request # needed as we have the request as a dependency here
        tags:
            - { name: knp_menu.menu, alias: main } # The alias is what is used to retrieve the menu