parameters:
#    wagaia_cms.example.class: Wagaia\Bundle\CMSBundle\Example

services:
#    wagaia_cms.example:
#        class: %wagaia_cms.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
